
server:
  port: 8888
spring:
  application:
    name: Spring Cloud server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jesintha/spring-boot-config-repo.git

  config:
    name: configserver